# Lab 10 - Textual Data Analytics
Complete the code with TODO tag.
## 1. Feature Engineering
In this exercise we will understand the functioning of TF/IDF ranking. Implement the feature engineering and its application, based on the code framework provided below.

First we use textual data from Twitter.

In [1]:
import numpy as np
import pandas as pd
data = pd.read_csv('elonmusk_tweets.csv')
print(len(data))
data.head()

2819


id           created_at  \
0  849636868052275200  2017-04-05 14:56:29   
1  848988730585096192  2017-04-03 20:01:01   
2  848943072423497728  2017-04-03 16:59:35   
3  848935705057280001  2017-04-03 16:30:19   
4  848416049573658624  2017-04-02 06:05:23   

                                                text  
0  b'And so the robots spared humanity ... https:...  
1  b"@ForIn2020 @waltmossberg @mims @defcon_5 Exa...  
2      b'@waltmossberg @mims @defcon_5 Et tu, Walt?'  
3                b'Stormy weather in Shortville ...'  
4  b"@DaveLeeBBC @verge Coal is dying due to nat ...

### 1.1. Text Normalization
Now we need to normalize text by stemming, tokenizing, and removing stopwords.

In [10]:
from __future__ import print_function, division
from nltk.stem import PorterStemmer, WordNetLemmatizer
import nltk
import string
from nltk.corpus import stopwords
import math
from collections import Counter
nltk.download('stopwords')
nltk.download('punkt')
import pprint 
pp = pprint.PrettyPrinter(indent=4)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\s5094000\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\s5094000\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


In [5]:
original_documents = [x.strip() for x in data['text']] 

In [114]:
import re

def normalize(document):
    # Remove prefix 'b'
#     document = re.sub(r"^b", "", document)
    
    # TODO: remove punctuation
    apostrophe = "'"
    # Remove all apostrophes, commas, semi-colons, ellipses
    text = re.sub(r"[^\w\s]", "", document)
    
    # TODO: tokenize text
    tokens = nltk.word_tokenize(text)
    
    # TODO: Stemming
    # This removes "morphological affixes"
    stemmer = PorterStemmer()
    ret = [stemmer.stem(word) for word in tokens]
    return ret

documents = [normalize(d) for d in original_documents]
documents[0]

['band', 'so', 'the', 'robot', 'spare', 'human', 'httpstcov7jujqwfcv']

As you can see that the normalization is still not perfect. Please feel free to improve upon (OPTIONAL), e.g. https://marcobonzanini.com/2015/03/09/mining-twitter-data-with-python-part-2/

### 1.2. Implement TF-IDF
Now you need to implement TF-IDF, including creating the vocabulary, computing term frequency, and normalizing by tf-idf weights.

In [47]:
stop_words = stopwords.words('english')

In [128]:
# Flatten all the documents
flat_list = [word for doc in documents for word in doc]

# TODO: remove stop words from the vocabulary
stop_words = stopwords.words('english')
words = [word for word in flat_list if word not in stop_words]

# TODO: we take the 500 most common words only
counts = Counter(words)
vocabulary = counts.most_common(500)
print([x for x in vocabulary if x[0] == 'tesla'])
vocabulary = [x[0] for x in vocabulary]
assert len(vocabulary) == 500

# vocabulary.sort()
vocabulary[:5]

[('tesla', 287)]


['brt', 'tesla', 'spacex', 'model', 'thi']

In [129]:
def tf(vocabulary, documents):
    matrix = [0] * len(documents)
    for i, document in enumerate(documents):
        counts = Counter(document)
        matrix[i] = [0] * len(vocabulary)
        for j, term in enumerate(vocabulary):
            matrix[i][j] = counts[term]
    return matrix

tf = tf(vocabulary, documents)
np.array(vocabulary)[np.where(np.array(tf[1]) > 0)], np.array(tf[1])[np.where(np.array(tf[1]) > 0)]

(array(['tesla', 'exactli'], dtype='<U17'), array([1, 1]))

In [147]:
import math

def _idf(vocabulary, documents):
    """TODO: compute IDF, storing values in a dictionary"""
    idf = {}
    
    # The number of documents in the corpus
    C = len(documents)
    
    for word in vocabulary:
        # The number of documents containing `word`
        C_t = sum([1 for document in documents if word in document])
        idf[word] = math.log((C/C_t), 2)
    
    return idf

idf = _idf(vocabulary, documents)
[idf[key] for key in vocabulary[:5]]

[2.539126825495932,
 3.3163095197385393,
 3.7262581423445837,
 3.8171115727956972,
 3.8027562798186274]

In [148]:
# def vectorize(documents, vocabulary, idf, tf):
#     document_vectors = [0] * len(documents)
#     for i, document in enumerate(documents):
#         document_vectors[i] = [0] * len(vocabulary)
#         for j, term in enumerate(vocabulary):
#             document_vectors[i][j] = idf[term] * tf[i][j]
#     return document_vectors

def vectorize(document, vocabulary, idf):
    vector = [0]*len(vocabulary)
    counts = Counter(document)
    for i,term in enumerate(vocabulary):
        vector[i] = idf[term] * counts[term]
    return vector

document_vectors = [vectorize(s, vocabulary, idf) for s in documents]
np.array(vocabulary)[np.where(np.array(document_vectors[1]) > 0)], np.array(document_vectors[1])[np.where(np.array(document_vectors[1]) > 0)]

(array(['tesla', 'exactli'], dtype='<U17'), array([3.31630952, 6.65361284]))

### 1.3. Compare the results with the reference implementation of scikit-learn library.

Now we use the scikit-learn library. As you can see that, the way we do text normalization affects the result. Feel free to further improve upon (OPTIONAL), e.g. https://stackoverflow.com/questions/36182502/add-stemming-support-to-countvectorizer-sklearn

In [149]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

tfidf = TfidfVectorizer(analyzer='word', ngram_range=(1,1), min_df = 1, stop_words = 'english', max_features=500)

features = tfidf.fit(original_documents)
corpus_tf_idf = tfidf.transform(original_documents) 

sum_words = corpus_tf_idf.sum(axis=0)
words_freq = [(word, sum_words[0, idx]) for word, idx in tfidf.vocabulary_.items()]
print(sorted(words_freq, key = lambda x: x[1], reverse=True)[:5])
print('testla', corpus_tf_idf[1, features.vocabulary_['tesla']])

[('http', 163.54366542841234), ('https', 151.85039944652075), ('rt', 112.61998731390989), ('tesla', 95.96401470715628), ('xe2', 88.20944486346477)]
testla 0.3495243100660956


### 1.4.  Apply TF-IDF for information retrieval
We can use the vector representation of documents to implement an information retrieval system. We test with the query $Q$ = "tesla nasa"

In [159]:
from sklearn.metrics.pairwise import cosine_similarity

def cosine_similarity(v1,v2):
    """TODO: compute cosine similarity"""
    sumxx, sumxy, sumyy = 0, 0, 0
    result = sklearn.metrics.pairwise.cosine_similarity(v1, v2)
    return result

def search_vec(query, k, vocabulary, stemmer, document_vectors, original_documents):
    q = query.split()
    q = [stemmer.stem(w) for w in q]
    query_vector = vectorize(q, vocabulary, idf)
    
    # TODO: rank the documents by cosine similarity
    print(sklearn.metrics.pairwise.cosine_similarity(np.array(query_vector).reshape(-1,1)))
    scores = ...
    
    print('Top-{0} documents'.format(k))
    for i in range(k):
        print(i, original_documents[scores[i][1]])

query = "tesla nasa"
search_vec(query, 5, vocabulary, PorterStemmer(), document_vectors, original_documents)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Top-5 documents


TypeError: 'ellipsis' object is not subscriptable

We can also use the scikit-learn library to do the retrieval.

In [141]:
new_features = tfidf.transform([query])

cosine_similarities = linear_kernel(new_features, corpus_tf_idf).flatten()
related_docs_indices = cosine_similarities.argsort()[::-1]

topk = 20
print('Top-{0} documents'.format(topk))
for i in range(topk):
    print(i, original_documents[related_docs_indices[i]])

Top-20 documents
0 b'@ashwin7002 @NASA @faa @AFPAA We have not ruled that out.'
1 b"SpaceX could not do this without NASA. Can't express enough appreciation. https://t.co/uQpI60zAV7"
2 b'@NASA launched a rocket into the northern lights http://t.co/tR2cSeMV'
3 b'Whatever happens today, we could not have done it without @NASA, but errors are ours alone and me most of all.'
4 b'RT @NASA: Updated @SpaceX #Dragon #ISS rendezvous times: NASA TV coverage begins Sunday at 3:30amET: http://t.co/qrm0Dz4jPE. Grapple at  ...'
5 b"Deeply appreciate @NASA's faith in @SpaceX. We will do whatever it takes to make NASA and the American people proud."
6 b'@jlgolson Per the letter, Tesla paid $55/hr for *additional* services, so no.'
7 b'Playing Amish Paradise in my Tesla'
8 b'RT @NASA: The @SpaceX #Dragon capsule passed directly below the #ISS at a distance of 2.5km, fulfilling all demonstration objectives for ...'
9 b'@NASA Best of luck to the Cygnus launch'
10 b'Would also like to congratulate @Boeing